# Generated by Django 5.0 on 2023-12-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_date_contact_update_date_contact_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='update_date',
        ),
        migrations.AlterField(
            model_name='contact',
            name='create_date',
            field=models.DateField(),
        ),
    ]
